import React from 'react';
import { AlertCircle, CheckCircle2, Info } from 'lucide-react';

export interface FeedbackCardProps {
    colorName: string;      // e.g., 'error', 'success', 'warning', 'info'
    isDarkMode?: boolean;
    children: React.ReactNode;
}

export const FeedbackCard: React.FC<FeedbackCardProps> = ({ colorName, isDarkMode, children }) => {
    // Sanitize the global color name for the CSS var prefix
    const safeName = colorName.toLowerCase().replace(/\s+/g, '-');

    // Determine the exact CSS prefix as generated by theme-mapper or theme-context
    let cssPrefix = `color-global-${safeName}`;
    if (['neutral', 'success', 'error'].includes(safeName)) {
        cssPrefix = `color-${safeName}`;
    }

    // In Light mode:
    // BG: Step 50 (faint tint)
    // Text: Step 700 or 800 (high contrast)

    // In Dark mode:
    // BG: Step 900 (dark tint)
    // Text: Step 200 or 300 (bright contrast)

    const bgStep = isDarkMode ? '900' : '50';
    const textStep = isDarkMode ? '300' : '700';

    const style: React.CSSProperties = {
        background: `var(--${cssPrefix}-${bgStep})`,
        color: `var(--${cssPrefix}-${textStep})`,
        padding: '0.875rem 1rem',
        borderRadius: '6px',
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        fontSize: '0.875rem',
        fontWeight: 500,
        lineHeight: 1.5,
    };

    // Determine a rudimentary icon based on the name strings
    let IconComponent = Info;
    if (safeName.includes('error') || safeName.includes('critical') || safeName.includes('warning') || safeName.includes('caution')) {
        IconComponent = AlertCircle;
    } else if (safeName.includes('success')) {
        IconComponent = CheckCircle2;
    }

    return (
        <div style={style}>
            <IconComponent size={20} strokeWidth={2} style={{ flexShrink: 0 }} />
            <div>{children}</div>
        </div>
    );
};
